// Automatically generated by the Thrifty compiler; do not edit!
// Generated on: 2017-02-19T11:45:33.009Z
// Source: /Users/nico/Documents/projekte/msc-webrtc/thrifty/webrtc.thrift at 24:1
package de.lespace.apprtc.thrift;

import com.microsoft.thrifty.service.ServiceMethodCallback;

public interface Webrtc {
  void call(Call call, ServiceMethodCallback<CallResult> callback);

  void registerUserId(RegisterUserId registerUserId,
      ServiceMethodCallback<RegisterResult> callback);
}
